<?xml version="1.0" encoding="utf-8"?><Database Name="AddressBook" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DYLAN-PC;Initial Catalog=AddressBook;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False" SettingsObjectName="CSharpFormsSQL.Properties.Settings" SettingsPropertyName="AddressBookConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Contacts" Member="Contacts">
    <Type Name="Contact">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Date_Added" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Company" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Website" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Forename" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Surname" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="County" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Postcode" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(320)" CanBeNull="true" />
      <Column Name="Mobile" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Notes" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
    </Type>
  </Table>
</Database>